#++++++++++++++++++++++++++++++++++++++
# MongoDB Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   mongo - official MongoDB
#               https://hub.docker.com/_/mongo/
#
#++++++++++++++++++++++++++++++++++++++

FROM mongo